### ISSUE TITLE
change readme

### ISSUE THREAD

**Issue by IIIdefconIII** [robertklep/dsm7-usb-serial-drivers#10]
with the content of usb-serial-drivers.sh it didnt work. I made a startup.sh myself with the following:

ash-4.4# vi startup.sh
sudo insmod /lib/modules/usbserial.ko
sudo insmod /lib/modules/ftdi_sio.ko
sudo chmod 777 /lib/modules/usbserial.ko
sudo chmod 777 /lib/modules/ftdi_sio.ko
sudo insmod /lib/modules/cdc-acm.ko
sudo insmod /lib/modules/cp210x.ko
sudo insmod /lib/modules/ch341.ko

after a reboot it worked like a charm, or i had to reboot, or i had to use this startup.sh instead not sure which mode activated it

**Comment by robertklep** [comment]
There was an issue in the README on how to start the provided script from the command line, which I now fixed. AFAIK, the provided script does work just fine on boot.

You can leave out the `chmod` commands from your script, they are superfluous.
