### ISSUE TITLE
Unknown symbol V1000 DS1821+

### ISSUE THREAD

**Issue by bertybassett** [robertklep/dsm7-usb-serial-drivers#109]
Synology Model DS1821+
CPU v1000

DMS DSM 7.2.1-69057 Update 1

Ran this script but no joy

sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/v1000/dsm-7.2/ch341.ko
sudo insmod /lib/modules/ch341.ko

sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/v1000/dsm-7.2/cp210x.ko
sudo insmod /lib/modules/cp210x.ko

sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/v1000/dsm-7.2/pl2303.ko
sudo insmod /lib/modules/pl2303.ko

sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/v1000/dsm-7.2/ti_usb_3410_5052.ko
sudo insmod /lib/modules/ti_usb_3410_5052.ko

I get  "unknown symbol in module" for all file drivers

insmod: ERROR: could not insert module /lib/modules/ch341.ko: Unknown symbol in module
`

<img width="629" alt="Screenshot 2023-10-31 at 20 57 58" src="https://github.com/robertklep/dsm7-usb-serial-drivers/assets/5606175/fde300e5-96a2-4556-b5f7-a8d656b2c50b">

<img width="905" alt="Screenshot 2023-10-31 at 21 29 28" src="https://github.com/robertklep/dsm7-usb-serial-drivers/assets/5606175/52f1bbbf-d402-4507-97f5-cffa1c54603b">

**Comment by bertybassett** [comment]
noticed this could it be something?

root@SynologyNAS:/lib/modules# grep -ao 'vermagic=[0-9.]\+' usbserial.ko 
vermagic=4.4.180

**Comment by robertklep** [comment]
Did you actually load `usbserial.ko` before the others?

**Comment by bertybassett** [comment]
I think I over write the usbserial.ko with a file from somewhere else. 

This was working last week using the  files from here and the .sh script then I upgraded dms a few spine points and additional the .ko files were missing. 

I quickly re-copied what I thought was the 7.2 .ko files back to lib\modules but I think I copied a rouge 7.0 usbserial.ko as well. 

Any idea who I test if my usbserial.ko is from 7.0?  


might log a support call with Synology support and see if they will send me a 7.2 usbserial file. 

Does compiling the files by hand create the usbserial.ko.

**Comment by robertklep** [comment]
What happens if you try to load `usbserial.ko`?

Compiling manually will not create `usbserial.ko`, because it's already supplied by DSM itself.

**Comment by bertybassett** [comment]
reboot just because then


<img width="693" alt="Screenshot 2023-11-01 at 09 32 00" src="https://github.com/robertklep/dsm7-usb-serial-drivers/assets/5606175/78516486-0456-431e-8680-d282c4fe49d0">

**Comment by robertklep** [comment]
Yes, that looks like it has been overwritten 🙁 It's not likely to be a version for an older kernel, because that would yield a different error.

You need to find someone that has the same NAS (or at least the same platform) to provide you with the correct copy of that file, or (possibly) download your current firmware from Synology and try to install it again.

**Comment by bertybassett** [comment]
dmesg confirm my thoughts I think

![Uploading Screenshot 2023-11-01 at 11.24.15.png…]()

**Comment by robertklep** [comment]
Your screenshot isn't showing 😅

**Comment by bertybassett** [comment]
![Uploading Screenshot 2023-11-01 at 11.24.15.png…]()

**Comment by bertybassett** [comment]
yes we are on the same page ,99% sure usbserial.ko is from DSM 7.0 and needs to be from 7.2

**Comment by bertybassett** [comment]
yeap was the wrong version of usbserial.ko

installed xpnology v1000 and extracted a working file, re-imported and rebooted real sysnology and ttyUSB0 appeared

**Comment by robertklep** [comment]
Ah, good thinking! Glad to see it's solved 👍🏻
