### ISSUE TITLE
Include PL2303 driver (for braswell)?

### ISSUE THREAD

**Issue by jamospo** [robertklep/dsm7-usb-serial-drivers#11]
It would be great if you could include pl2303.ko. Currently I'd need it for a braswell system.

**Comment by robertklep** [comment]
I compiled [pl2303.ko](https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules/braswell) for Braswell. I had some issues during compilation so please let me know if it works :D

**Comment by jamospo** [comment]
Works as expected :-) thanks for your support!
