### ISSUE TITLE
Can you compile a AQC107 driver?

### ISSUE THREAD

**Issue by 007revad** [robertklep/dsm7-usb-serial-drivers#111]
Can you do me a big favor and compile the attached Marvell Linux 2.5.6 AQC107 driver for x86_64 Geminilake DSM 7.2 ?

It's for a little project that was discussed [on reddit](https://www.reddit.com/r/synology/comments/188tw4a/comment/kbo76ai/?context=3) inspired by an [article on Tom's Hardware](https://www.tomshardware.com/networking/10-gigabit-ethernet-slots-into-your-m2-port-costs-only-dollar86).

[marvell_linux_2.5.6_aqc107.zip](https://github.com/robertklep/dsm7-usb-serial-drivers/files/13627574/marvell_linux_2.5.6_aqc107.zip)

**Comment by robertklep** [comment]
Sorry, this repo is for USB-to-serial drivers only, which is pretty much the only thing I know how to compile 😅
