### ISSUE TITLE
Epyc7002 drivers

### ISSUE THREAD

**Issue by xavier-thomas** [robertklep/dsm7-usb-serial-drivers#114]
Hi,

Is there a possibility to add drivers for the Epyc7002 platform ?
I'm trying to use a zigbee USB device on a Synology SA6400

Kernel version is: 5.10

I can see the device being detected on the USB hub by the `lsusb` command, but doesn't seem to be mounted (I presume due to the lack of drivers).

![image](https://github.com/robertklep/dsm7-usb-serial-drivers/assets/38254298/ba58c4dc-f5b1-4d17-8894-403a1662707f)

**Comment by robertklep** [comment]
Have you tried the drivers that come with DSM?
```
sudo insmod /lib/modules/usbserial.ko
sudo insmod /lib/modules/cdc-acm.ko
```

If that doesn't work: I'm in the process of migrating my Unraid server, which means I can't access the virtual machine in which I build these modules. So it may take some time before I will be able to build additional drivers.

**Comment by xavier-thomas** [comment]
Hi @robertklep, that actually worked. I hadn't realised that DSM 7.2 shipped with native usb drivers.

**Comment by robertklep** [comment]
@xavier-thomas yeah they left _some_ drivers 😅
