### ISSUE TITLE
Epyc7002 modules for usb

### ISSUE THREAD

**Issue by error105** [robertklep/dsm7-usb-serial-drivers#116]
Hi, there is any chance that u will prepare ch340 and other for Epyc7002 (SA6400) with kernel 5.10.55+ ?

**Comment by robertklep** [comment]
I'll take a look. I assume that it's running DSM 7.2?

**Comment by error105** [comment]
> I'll take a look. I assume that it's running DSM 7.2?
> 
> Also, what device are you looking to add support for? In my experience, the DSM-built-in `cdc-acm.ko` module already covers the most popular devices.

Yes, 7.2 DSM :) I have cc2652 zigbee coordinator with ch340 usb-uart, also I want connect my TevoTarantula to use it with Klipper on docker.

**Comment by robertklep** [comment]
Try these: https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules/epyc7002/dsm-7.2

(make sure to follow the [downloading instructions](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module))

**Comment by error105** [comment]
> Try these: https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules/epyc7002/dsm-7.2
> 
> (make sure to follow the [downloading instructions](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module))

Thanx, i will try evening and will let u know :)

**Comment by error105** [comment]
> Try these: https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules/epyc7002/dsm-7.2
> 
> (make sure to follow the [downloading instructions](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module))

Works perfect !! ur awesome.

**Comment by robertklep** [comment]
Thanks for testing! 👍🏻
