### ISSUE TITLE
Add driver for PL2303 on avoton 

### ISSUE THREAD

**Issue by fdebrus** [robertklep/dsm7-usb-serial-drivers#12]
I've tried by myself, but... 

Is anyone successful building the PL2303 ? alternatively I can purchase another USB-2-Serial that is nativly supported if any.

thanks !

`
====================================
                Start to run "Build Package"
------------------------------------------------------------
[avoton] env PackageName=3.10.x /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 7.0 3.10.x
Set cache size limit to 8.0 Gbytes
Statistics cleared
[INFO] projectList=3.10.x
[INFO] Start to build 3.10.x.
**[Error] There is no build scripts for 3.10.x**
`

**Comment by robertklep** [comment]
@fdebrus I was having some issues building the PL2303 driver for Braswell (see #11) but in the end managed to get it compiled. I'll see if I can compile one for Avoton too.

**Comment by fdebrus** [comment]
Thank you ! working as expected. 

`root@nas-1:/lib/modules# lsusb
|__usb1          1d6b:0002:0310 09  2.00  480MBit/s 0mA 1IF  (ehci_hcd 0000:00:16.0) hub
  |__1-1         8087:07db:0002 09  2.00  480MBit/s 0mA 1IF  ( ffffffd1ffffffb2ffffffdbffffffad) hub
    |__1-1.1     f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 65004C20C3343931)
|__usb2          1d6b:0002:0310 09  2.00  480MBit/s 0mA 1IF  (Linux 3.10.108 etxhci_hcd-170202 Etron xHCI Host Controller 0000:04:00.0) hub
  |__2-4         067b:2303:0400 00  1.10   12MBit/s 100mA 1IF  (Prolific Technology Inc.  USB-Serial Controller D fffffff0ffffffd0ffffffa2fffff                     fc7)
|__usb3          1d6b:0003:0310 09  3.00 5000MBit/s 0mA 1IF  (Linux 3.10.108 etxhci_hcd-170202 Etron xHCI Host Controller 0000:04:00.0) hub
  |__3-1         18d1:9302:0100 00  3.10 5000MBit/s 896mA 1IF  ( ffffffd1ffffffb2ffffffdbffffffa0)
root@nas-1:/lib/modules# ll /dev/ttyU*
crw------- 1 root root 188, 0 Oct 19 11:58 /dev/ttyUSB0
`
