### ISSUE TITLE
USB Support for Evansport DSM 7.1 is not present

### ISSUE THREAD

**Issue by steveeadams** [robertklep/dsm7-usb-serial-drivers#122]
Looking (if you have time) for the Serial drivers for an Evansport running DSM 7.1 (more specifically 7.1.1-42962 update 6)
  
uname -a output: 
Linux Diskstation 3.2.101 #42962 SMP PREEMPT Mon May 29 14:34:28 CST 2023 i686 GNU/Linux synology_evansport_214play

Serial driver for: 
Sonoff Zigbee 3.0 USB Dongel plus e

**Comment by robertklep** [comment]
I think the Sonoff dongle requires the ch340.ko module, check out https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules/evansport/dsm-7.1

**Comment by steveeadams** [comment]
Thank you so much !
