### ISSUE TITLE
Install Sonoff module E in Synology DSM918+ Apollolake /dev/ttyUSB0 not found 

### ISSUE THREAD

**Issue by pf2002** [robertklep/dsm7-usb-serial-drivers#123]
Hi 
It is the first time I install Sonoff or any USB interface in my Synology DS918+
My Synology version DSM 7.2(5).
The problem when I added the Sonoff directly to the NAS or via A cable in /dev only ttyACM0 was available, /dev/ttyUSB0 is not found.
I rebooted the synology and launch:
modprobe usbserial
modprobe ftdi_sio
modprobe cdc-acm
but it didn't fix the problem.

I presume all modules are loaded correctly: 
xxxx@NasHomeSyn:/lib/modules$ ls -l usbserial.ko ftdi_sio.ko cdc-acm.ko cp210x.ko ch341.ko pl2303.ko
-rw-r--r-- 1 root root  45811 Sep 23  2023 cdc-acm.ko
-rw------- 1 root root 256048 May 20 14:50 ch341.ko
-rw------- 1 root root 273104 May 20 14:50 cp210x.ko
-rw-r--r-- 1 root root 127499 Sep 23  2023 ftdi_sio.ko
-rw------- 1 root root 278328 May 20 14:50 pl2303.ko
-rw-r--r-- 1 root root  48059 Sep 23  2023 usbserial.ko 

When I run again below commands I have a message - insmod: ERROR: could not insert module /lib/modules/xxx File exists
sudo insmod /lib/modules/usbserial.ko
sudo insmod /lib/modules/ftdi_sio.ko
sudo insmod /lib/modules/cdc-acm.ko
sudo insmod /lib/modules/cp210x.ko
sudo insmod /lib/modules/ch341.ko
sudo insmod /lib/modules/pl2303.ko
Please note that at the first time launchig above commands there was no error.

xxxx@NasHomeSyn:/lib/modules$ uname -u
synology_apollolake_918+

xxxx@NasHomeSyn:/lib/modules$ lsmod | grep usbserial
usbserial              22534  5 ch341,cp210x,ti_usb_3410_5052,pl2303,ftdi_sio
usbcore               210297  17 ch341,ch343,etxhci_hcd,usblp,uhci_hcd,usb_storage,cp210x,usbserial,ti_usb_3410_5052,ehci_hcd,ehci_pci,pl2303,usbhid,ftdi_sio,cdc_acm,xhci_hcd,xhci_pci

xxxx@NasHomeSyn:/lib/modules$ sudo dmesg | grep -i usb
[ 3135.503540] usbcore: registered new interface driver usb_ch343
[ 3135.503562] ch343: USB serial driver for ch342/ch343/ch344/ch347/ch9101/ch9102/ch9103/ch9143, etc.

```
xxxx@NasHomeSyn:/lib/modules$ lsusb -cui
|__usb1          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.302+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__1-3         1a86:55d4:0442 02  1.10   12MBit/s 132mA 2IFs (ITEAD SONOFF Zigbee 3.0 USB Dongle Plus V2 20240122200556)
  1-3:1.0         (IF) 02:02:01 1EP  () cdc_acm tty/ttyACM0
  1-3:1.1         (IF) 0a:00:00 2EPs () cdc_acm
  |__1-4         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 6500813E2CDA5A53)
  1-4:1.0         (IF) 08:06:50 2EPs () usb-storage host5 (synoboot)
```

I hope that you have an idea about the issue.
and thanks in advance for your support.
Philippe

**Comment by pf2002** [comment]
Thanks very much for your support. 
Now I can see zigbee2mqtt is able to open the serial port, however  failed with below error message:
« 2024/05/24 22:58:12,stdout,[2024-05-24 22:58:12] e[31merrore[39m: z2m: Failed to start zigbee »

« 2024/05/24 22:58:12,stdout,[2024-05-24 22:58:12] e[31merrore[39m: z2m: Error while starting zigbee-herdsman »

« 2024/05/24 22:57:54,stdout,[2024-05-24 22:57:54] e[32minfoe[39m: zh:zstack:znp: Skip bootloader for CC2652/CC1352 »

« 2024/05/24 22:57:52,stdout,[2024-05-24 22:57:52] e[32minfoe[39m: zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload »

« 2024/05/24 22:57:52,stdout,[2024-05-24 22:57:52] e[32minfoe[39m: zh:zstack:znp: Serialport opened »

« 2024/05/24 22:57:52,stdout, »« [2024-05-24 22:57:52] e[32minfoe[39m: zh:zstack:znp: Opening SerialPort with {"« path" »:" »/dev/ttyACM0"« ,"« baudRate" »:115200,"« rtscts" »:false,"« autoOpen" »:false} »


Zigbee2mqtt configuration.yaml:
Ma configuration de zigbee2mqtt confiuration.yaml :
homeassistant: true
permit_join: true
mqtt:
base_topic: zigbee2mqtt
server: ‹ mqtt://192.168.1.26:1883 ›
client_id: zigbee2mqtt
include_device_information: true
serial:
port: /dev/ttyACM0
#port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_ 20240122200556-if00-port0
adapter: ezsp

frontend:
port: 8020

Do you have an idea where the problem could be ?
thanks again for your support.

**Comment by robertklep** [comment]
Have you flashed the dongle with the correct zigbee2mqtt firmware? https://www.zigbee2mqtt.io/guide/adapters/emberznet.html#firmware-flashing

FWIW, I can't provide you with a lot of support for zigbee2mqtt-related issues, you may need to find a more specific forum for that.
