### ISSUE TITLE
Just here to say thanks 

### ISSUE THREAD

**Issue by piejanssens** [robertklep/dsm7-usb-serial-drivers#124]
Thanks for your efforts.
You can add RTK.GPIO to the list of devices that can be useful on a Synology NAS.
This small USB device bridges the digital and physical worlds. 
Useful to add hardware sensors directly on the Synology and use them in applications such as Homebridge.

**Comment by robertklep** [comment]
Thanks! 😄

Never heard of that device, looking at it now and it looks very useful. Might order one myself 👍🏻
