### ISSUE TITLE
Synology ds923+ and  Sonoff Zigbee 3.0 USB Dongle Plus

### ISSUE THREAD

**Issue by gawronix** [robertklep/dsm7-usb-serial-drivers#131]
I did yors instruction without any problems to the point with command : lsusb -cui
Im not able to see the name of USB on ds923+ . Please help what you need more to help me resolve the issue ?

  |__1-3         10c4:ea60:0100 00  1.10   12MBit/s 100mA 1IF  (Silicon Labs Sonoff Zigbee 3.0 USB Dongle Plus 0001)
  1-3:1.0         (IF) ff:00:00 2EPs ()

when I'm trying to sudo chmod 666 /dev/ttyUSB0
chmod: cannot access '/dev/ttyUSB0': No such file or directory

The script is loading the correct RAW files upload and copied [cp210x.ko](https://github.com/robertklep/dsm7-usb-serial-drivers/blob/main/modules/r1000/dsm-7.2/cp210x.ko)

WHAT IM MISSING ?!

**Comment by gawronix** [comment]
:/$ /usr/syno/bin/lsusb -cui
|__usb1          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.302+ xhci-hcd xHCI Host Controller 0000:08:00.3) hub
  |__1-1         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 650047DFB7238D86)
  1-1:1.0         (IF) 08:06:50 2EPs () usb-storage host7 (synoboot)
  |__1-3         10c4:ea60:0100 00  1.10   12MBit/s 100mA 1IF  (Silicon Labs Sonoff Zigbee 3.0 USB Dongle Plus 0001)
  1-3:1.0         (IF) ff:00:00 2EPs ()

**Comment by robertklep** [comment]
What's the output of the command `lsmod | grep serial`?

**Comment by gawronix** [comment]
![Zrzut ekranu 2024-12-17 171528](https://github.com/user-attachments/assets/0612f362-7fcb-4171-94bb-17e78aa9267b)
sadly nothing :(

**Comment by gawronix** [comment]
![Zrzut ekranu 2024-12-17 172939](https://github.com/user-attachments/assets/2eb7b172-ff0d-45f3-8fbf-9580de354c82)

**Comment by gawronix** [comment]
its just putty thing, im not including anything

**Comment by gawronix** [comment]
![Zrzut ekranu 2024-12-17 173959](https://github.com/user-attachments/assets/a3df02b9-69d0-4f27-a893-46f829b9fa66)

**Comment by robertklep** [comment]
> its just putty thing, im not including anything

Yes, you are. There's an extra `# ` before the command that needs to be removed:
<img width="510" alt="image" src="https://github.com/user-attachments/assets/853e5359-6ee8-486e-b6bd-fe1d4957a536" />

The reason it was shown in the README is because by convention, it means that the command needs to be run as root. I've updated the README to remove any confusion.

**Comment by gawronix** [comment]
Thanks. Now I need to get this work done in HA 👍

**Comment by robertklep** [comment]
Good luck!
