### ISSUE TITLE
DSM 7.1 beta compatibility.

### ISSUE THREAD

**Issue by Benoitone** [robertklep/dsm7-usb-serial-drivers#22]
I have a DS918+ on DSM 7 and your drivers works well on it.
Do you know if they are ok on the beta 7.1?
Thanks for your work!!!

**Comment by robertklep** [comment]
I don't know if they'll work, would be very interested in hearing if they do (if only so I know I can safely upgrade to 7.1 when it's stable) 😅

**Comment by Benoitone** [comment]
I have install DSM 7.1 beta and drivers seem to work fine... for my RFXTx433 ;-)

**Comment by Ekim0789** [comment]
I have also installed these drivers on my DS920+ running DSM 7.1 (non beta) and it is working just fine! A quick uname -a shows that the Linux kernel is still 4.4.x.

**Comment by Ekim0789** [comment]
I have also installed these drivers on my DS920+ running DSM 7.1 (stable) and it is working just fine! A quick uname -a shows that the Linux kernel is still 4.4.x.

**Comment by Benoitone** [comment]
Since I upgrade to 7.1-42661 Update 2 my Apollolake Nas, drivers seems to not works :-(

**Comment by Ekim0789** [comment]
> Since I upgrade to 7.1-42661 Update 2 my Apollolake Nas, drivers seems to not works :-(
> Does someone have this issue too?

I haven't updated to Update 2 yet. Did it maybe wipe out your startup script or something?

**Comment by robertklep** [comment]
@Benoitone:
> Since I upgrade to 7.1-42661 Update 2 my Apollolake Nas, drivers seems to not works :-(

What exactly does that mean? Are you getting any errors?

**Comment by Benoitone** [comment]
Indeed, the drivers are deleted from the modules folder. The script is still there after the update. However, even after returning the drivers, the USB port is not recognised.

**Comment by robertklep** [comment]
That means it's already loaded.

**Comment by robertklep** [comment]
Also, the output of `lsusb -i` might be interesting, please post it while the device is plugged in.

**Comment by Benoitone** [comment]
Hello, I find my problem... it's not a drivers issue but a problem with files permissions of the copied drivers in /lib/modules directory.
I think I have make a mistake and transfer the drivers with my admin account and not as root.
I have change owner of the drivers and my problem was solved!!!
Thanks a lot for you help.

**Comment by robertklep** [comment]
Thank you for the update! I'll close the issue 😊

**Comment by lappat** [comment]
Hi,
i have update DSM from 7.0 to 7.1 this morning and Zwave to MQTT have a error:

Driver: Failed to open the serial port: Error: No such file or directory, cannot open /dev/ttyUSB0

i have Zwave to Mqtt install on docker and everything was working fine before update.

any help will be welcome.

regards

**Comment by baylanger** [comment]
@lappat https://www.reddit.com/r/synology/comments/tz1f0r/comment/ibid53t/?utm_source=share&utm_medium=web2x&context=3

**Comment by Ekim0789** [comment]
Sorry to necro this, just wanted to say that I updated to the 7.1.1-42951 Release Candidate and these drivers work just fine on my DS920+. Thanks!

**Comment by rruber** [comment]
After upgrade to DSM 7.1-42661 Update 4 from DSM 7.1-42661 Update 2, the driver file "usbserial" disappeared and consequentially it no longer works. There is no ttyUSB device.

**Comment by Ekim0789** [comment]
> After upgrade to DSM 7.1-42661 Update 4 from DSM 7.1-42661 Update 2, the driver file "usbserial" disappeared and consequentially it no longer works. There is no ttyUSB device.

you have to install it again

**Comment by robertklep** [comment]
@Ekim0789 up uptil now, `usbserial` was installed by default on DSM, only the other drivers weren't. It's a bit worrying that Synology is now also deleting `usbserial` (one of the reasons why I'm moving away from Synology and in the middle of an Unraid build...).

**Comment by Ekim0789** [comment]
Oh sorry I must have misread that, I'm on 7.1.1 and I never had usbserial get deleted.
