### ISSUE TITLE
realtek8125 pci-e drivers dsm7

### ISSUE THREAD

**Issue by jdcruz78** [robertklep/dsm7-usb-serial-drivers#25]
Greeting

i would like some help, i have a NIC 2.5GB with realtek chip and i own a synology rs2421. if it is not to much to ask i would like someone to create a pak for this pci-e card

**Comment by robertklep** [comment]
This repository is only for USB-based serial devices. Besides that, was your device ever supported by DSM6?

In any case, it's too difficult for me 🥴

**Comment by jdcruz78** [comment]
Not for dsm6, but any way thanks for reply back

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 26, 2022 at 10:09 AM, Robert ***@***.***> wrote:   


This repository is only for USB-based serial devices. Besides that, was your device ever supported by DSM6?

In any case, it's too difficult for me 🥴
