### ISSUE TITLE
i have deleted serialusb.ko 

### ISSUE THREAD

**Issue by vocaris9** [robertklep/dsm7-usb-serial-drivers#28]
Sorry,
but I accidentally deleted the file serialisb.ko mit rm.
I habe a DS220+
Where can i find/download this file?

**Comment by robertklep** [comment]
It's part of DSM itself. If you have DSM updates pending, that might be a way to get it back, otherwise find someone with the same architecture ([Geminilake](https://kb.synology.com/en-uk/DSM/tutorial/What_kind_of_CPU_does_my_NAS_have)) to send you the file from their Synology (I have Apollolake so can't help there, I'm afraid).

**Comment by vocaris9** [comment]
OK. Thank you.

**Comment by baylanger** [comment]
@vocaris9 

```
# uname -a
Linux san 4.4.180+ #42661 SMP Mon Jun 27 15:07:20 CST 2022 x86_64 GNU/Linux synology_geminilake_720+
# ls -l /usr/lib/modules/usbserial.ko
-rw-r--r-- 1 root root 46875 Apr  1 05:53 /usr/lib/modules/usbserial.ko
# md5sum /usr/lib/modules/usbserial.ko
150581651ccc3b83157cb10665761584  /usr/lib/modules/usbserial.ko

GitHub didn't accept a .ko file ... so I was lazy and renamed it as a .pdf file.  Only once I post this reply that I'll know if the file is downloaded...  MAKE SURE to check md5sum matches before moving it into the "kernel modules" directory.  You should have make this file owned by root:root w/ 644 perms (like other files already in there).

```
![usbserial](https://user-images.githubusercontent.com/5240348/179404307-3f2867d4-2b35-47f6-9aea-440f707ad117.jpeg)

**Comment by baylanger** [comment]
It works.

From my Mac: 
```
% curl https://user-images.githubusercontent.com/5240348/179404307-3f2867d4-2b35-47f6-9aea-440f707ad117.jpeg -o usbserial.ko
% md5 usbserial.ko
MD5 (usbserial.ko) = 150581651ccc3b83157cb10665761584
```

**Comment by vocaris9** [comment]
@baylanger Thank you. It runs...

**Comment by robertklep** [comment]
@baylanger nice workaround! And thanks for the help 😁

**Comment by dominicsherry1** [comment]
I’ve made the same mistake but on DSM7.2.1-69057 update 5. @baylanger ’s file is for 7.1.1 I believe. Does anyone have a geminilake device with the latest update and able to share serialusb.ko with me please?

**Comment by dominicsherry1** [comment]
@Koky05 Can you rename it to png and attach it to a comment on this thread?

**Comment by Koky05** [comment]
![usbserial](https://github.com/robertklep/dsm7-usb-serial-drivers/assets/89223022/f39a76d3-e51d-4fa0-8ea7-84ca92058977)

**Comment by dominicsherry1** [comment]
It works. Thanks a lot!
