### ISSUE TITLE
Monaco and V1000

### ISSUE THREAD

**Issue by Pezantros** [robertklep/dsm7-usb-serial-drivers#3]
Hello,
Please, can you make some for Monaco (STM STiH412) and for V1000 (AMD Ryzen V1500B)?
Thank You very much!

**Comment by robertklep** [comment]
v1000 should be the same as apollolake/geminilake, I'd be interested in hearing if the modules for those platforms load okay if you're willing to try. It would save me some work ;) (if it doesn't work, I'll compile them for v1000 specifically).

I'll compile monaco tomorrow.

**Comment by robertklep** [comment]
I went ahead and added both v1000 and monaco.
