### ISSUE TITLE
R1000 versus V1000?

### ISSUE THREAD

**Issue by IdahoSnakeHouse** [robertklep/dsm7-usb-serial-drivers#31]
Are the R1000 drivers suitable for a V1000 device?  I tried to build from source using "v1000" as the architecture, but got an error suggesting there is no support for V1000.

I have a new DS1522+ and don't see a way forward to get driver support for my itead Zigbee 3.0 dongle.

**Comment by robertklep** [comment]
> Are the R1000 drivers suitable for a V1000 device?

I have no idea 😬 It should be relatively safe to try, though.

**Comment by IdahoSnakeHouse** [comment]
Thanks, tried the R1000 drivers and everything seems to be working ok.

**Comment by robertklep** [comment]
Good to hear!
