### ISSUE TITLE
Support  USB Tuner DVB-T2/C  ?

### ISSUE THREAD

**Issue by dnmnhat** [robertklep/dsm7-usb-serial-drivers#33]
I have 2 MyGica T230C USB DVB-T2/C.
I hope if you can support USB Tuner DVB-T2/C
Sorry I'm not familiar with the linux-kernel issue...
You can consult
https://github.com/SynoCommunity/spksrc/wiki/FAQ-SynocliKernel-(usbserial,-linuxtv)
https://github.com/th0ma7/synology

I need for DVB-T2/C TV in TVHeadend Server & Plex Server

**Comment by robertklep** [comment]
This project is only for USB serial drivers, which are relatively easy to compile. Anything more elaborate (like TV tuners, BLE/BT, etc) is beyond its scope, I'm afraid.
