### ISSUE TITLE
DS2419+ denverton support

### ISSUE THREAD

**Issue by sneery** [robertklep/dsm7-usb-serial-drivers#36]
Hi, need DSM7.1 driver for denverton cpu with 4.4.180+ kernel.
Tried compiling myself, (many times, different platforms) but even though instructions appear relatively easy, was well beyond my capabilities.
Thanks

**Comment by robertklep** [comment]
Have you tried the Jadahl drivers for Denverton?

The main website is offline but you can still find them here: https://web.archive.org/web/20211027123240/http://www.jadahl.com/iperf-arp-scan/DSM_7.0/denverton/

**Comment by sneery** [comment]
I have now. 
/dev/ttyUSB0 is alive!

Many Thanks
