### ISSUE TITLE
PL2303 Apollolake

### ISSUE THREAD

**Issue by erich74** [robertklep/dsm7-usb-serial-drivers#37]
Hi,
Thanks a lot for putting those resources available!
Could you please add PL2303 available for Apollolake (DS218+ for me) please?
I have a Zigate Zigbee (v1) using this serial interface, I could make it work using the following link https://web.archive.org/web/20220126180837/http://www.jadahl.com/iperf-arp-scan/DSM_7.0/apollolake/

but it would be nice if you could add it so that we can only keep your GH as a single source and reference!
Thanks a lot

**Comment by robertklep** [comment]
Done! I'll do the same for the other platforms, it's a shame that the Jadahl site is offline 😕

**Comment by erich74** [comment]
Thank you very much Robert. Yes this is a shame but we have your GH now as the reference ;)
