### ISSUE TITLE
cedarview driver for CH343

### ISSUE THREAD

**Issue by casperskj** [robertklep/dsm7-usb-serial-drivers#43]
Hi, can you supply a cedarview driver for CH9102.

I believe it is the CH343 driver.
https://github.com/WCHSoftGroup/ch343ser_linux

**Comment by robertklep** [comment]
I just pushed a version for DSM 7.1: https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules/cedarview/dsm-7.1

If you're still on 7.0, let me know.

**Comment by caslunar** [comment]
Thanks. I am on 7.1 so that's perfect. I will give it a go.
Thank you for helping out so quickly.
