### ISSUE TITLE
geminilake DSM 7.1: cp210x.ko: Invalid module format

### ISSUE THREAD

**Issue by ovidiu4** [robertklep/dsm7-usb-serial-drivers#46]
It seems that the modules don't work on my DS720+
I'm trying to get the Sonoff Zigbee 3.0 USB dongle to work ...
Any advice?

AAAAAAA:/lib/modules$ uname -a
Linux AAA **4.4.180**+ #42962 SMP Tue Sep 20 22:35:56 CST 2022 x86_64 GNU/Linux **synology_geminilake_720+**
AAAAAAA:/lib/modules$ sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/blob/main/modules/geminilake/dsm-7.1/cp210x.ko

2022-11-02 17:54:31 (1.25 MB/s) - 'cp210x.ko' saved [140128]

AAAAAAA:/lib/modules$ sudo insmod cp210x.ko
**insmod: ERROR: could not insert module cp210x.ko: Invalid module format**

**Comment by robertklep** [comment]
Take a look at #41, you're having the same issue (not downloading the correct URL).
