### ISSUE TITLE
is it possible to extract usb-dvbs-drivers from dsm 6.2.4 for your dsm 7 workaround

### ISSUE THREAD

**Issue by mgfirewater** [robertklep/dsm7-usb-serial-drivers#50]
i have a similar problem like in closed issue #33.
because i didn't found any usb tv stick driver for dsm 7.x.

do you believe it's possible to extract the usb driver of my pctv 461e usb-stick from dsm 6.2.4? 
And if that's possible. could i use your script to import the driver to dsm 7?
my ds218 runs unfortunately with this dsm version because i didn't found a way to use a tv usb stick with dsm 7.x

**Comment by robertklep** [comment]
It's very likely not possible because DSM 6 and DSM 7 are using different kernels, and the drivers are compiled against a specific kernel version.
