### ISSUE TITLE
WIFI N10 NANO RTL8192CU

### ISSUE THREAD

**Issue by TillHansi** [robertklep/dsm7-usb-serial-drivers#61]
Hi,

I successfully loaded the usbserial and ftdi modul, however seems there is no driver for this ASUS Wifi dongle available using the RTL8192CU chipset.

Would it be possible to provide this one for apollolake 918+?

Linux DiskStation 4.4.180+ #42962 SMP Sat Sep 3 22:30:29 CST 2022 x86_64 GNU/Linux synology_apollolake_918+

Many thanks!

**Comment by robertklep** [comment]
This repository is only for serial drivers, which are already a bit of a PITA to compile (and they are structurally quite easy, just a single source file).

I suspect that (much) more complex drivers, like for WiFi, will be even more problematic, so I'm afraid I'm not even going to try, sorry 🥴
