### ISSUE TITLE
geminilake dsm 7.1 drivers

### ISSUE THREAD

**Issue by fspnyc** [robertklep/dsm7-usb-serial-drivers#63]
Having trouble having my 220+ (DSM 7.1.1 kernel 42962 Update 2) NAS recognizing my HUSBZB (flashed), Has anyone compiled the ti_usb_3410_5052 and start-usb-drivers files for DSM7.1 yet?  Thinking this might be the culprit. Thank you!

**Comment by robertklep** [comment]
It does or it _doesn't_ recognize it? What does `lsusb -cui` show?

**Comment by fspnyc** [comment]
I unloaded the kernel files and reloaded them and now ttyUSB0 and ttyUSB1 now show up in lsusb! I guess I didn't need those additional files.  Now getting HA see it in my docker container is another challenge.  Thank you!

**Comment by robertklep** [comment]
Good luck, and have fun!
