### ISSUE TITLE
Synology 1522+

### ISSUE THREAD

**Issue by MontecristoGab** [robertklep/dsm7-usb-serial-drivers#81]
Hello. Looking for USB drivers for:

Linux G-NAS 4.4.180+ #42962 SMP Fri Feb 10 16:33:40 CST 2023 x86_64 GNU/Linux synology_r1000_1522+

Any help is greatly appreciated.

**Comment by robertklep** [comment]
R1000 drivers are available already: https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules/r1000
