### ISSUE TITLE
auto after rest of nas

### ISSUE THREAD

**Issue by pressurejets** [robertklep/dsm7-usb-serial-drivers#82]
just did a update  on dsm and it restarted, again usb is ls not there so re done all the 
 sudo chmod +x /usr/local/etc/rc.d/usb-serial-driver  
and start to get back working. 
working now, but is there away that it can be auto

**Comment by robertklep** [comment]
If the script didn't have executable permissions, it wouldn't have been run during startup. Now that it has the correct permissions, it should.

If it still doesn't work, you can also use Synology's Task Scheduler to schedule a task at boot up, which would then run the script.
