### ISSUE TITLE
Atheros wifi usb drivers

### ISSUE THREAD

**Issue by nickbolero** [robertklep/dsm7-usb-serial-drivers#83]
Hello, I wanted to ask you if there is a way to make DMS 7.1.1.42962 detect my usb wifi dongle. Since it used to work fine with DMS 6.1.
My system is a DS3622xs+ (XPEnology).
![Cattura2](https://user-images.githubusercontent.com/54214273/235325291-d695b406-7f8b-44a9-91d7-30ea091a42a5.JPG)
![Immagine WhatsApp 2023-04-29 ore 23 40 15](https://user-images.githubusercontent.com/54214273/235325322-a5427275-5fa2-4c6a-b845-9ba98ecfd5e0.jpg)

**Comment by robertklep** [comment]
Sorry, this repository is for USB serial drivers only, WiFi dongles have many more dependencies and I have no idea where to even start.
