### ISSUE TITLE
USB drivers for DS918+ DSM 7.2-64551 RC

### ISSUE THREAD

**Issue by fwiegers** [robertklep/dsm7-usb-serial-drivers#85]
Hi,

I have a problem loading cp210x.ko for DSM 7.2-654551 RC. The same driver worked ok for the previous release (DSM 7.2-64216) worked ok without any issues.

Kernel information:
Linux Wiegers_NAS 4.4.302+ #64551 SMP Fri Apr 28 19:48:21 CST 2023 x86_64 GNU/Linux synology_apollolake_918+

I hope you can help me out.

Regards,

Frans Wiegers

**Comment by robertklep** [comment]
Would be useful to know the actual problem you're having 😅

**Comment by baylanger** [comment]
Please provide the output that shows the error.

**Comment by fwiegers** [comment]
This is the output:

Frans@Wiegers_NAS:/lib/modules$ sudo insmod cp210x.ko
Password:
insmod: ERROR: could not insert module cp210x.ko: Invalid module format

**Comment by robertklep** [comment]
@fwiegers that means you very likely didn't download the correct file. See [the instructions in the README](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module).

**Comment by fwiegers** [comment]
@robertklep I tried again following your exact directions. Same result
Could there be a change between 7.2-654551 RC and 7.2-64216 causing this?

**Comment by robertklep** [comment]
@fwiegers what does `file /lib/modules/cp210x.ko` return?

**Comment by fwiegers** [comment]
Apparently 'file' is an unknown command in DSM? 
sudo: file: command not found.
Is there a way to switch to another shell?

**Comment by robertklep** [comment]
Ah sorry, I use an external package that provides `file`.

Try this:
```
tr -cd '[:print:]' < /lib/modules/cp210x.ko | head -c 50
```

**Comment by fwiegers** [comment]
I get "permission denied" also when I add sudo before the command.

**Comment by robertklep** [comment]
Try setting the correct permissions first: `sudo chmod 644 /lib/modules/cp210x.ko`

**Comment by fwiegers** [comment]
Frans@Wiegers_NAS:/lib/modules$ sudo tr -cd '[:print:]' < /lib/modules/cp210x.ko | head -c 50
<!DOCTYPE html><html lang="en" data-color-mode="au
This means is looks like a html document, right? So wrong way of downloading?

**Comment by fwiegers** [comment]
Frans@Wiegers_NAS:/lib/modules$ sudo tr -cd '[:print:]' < /lib/modules/cp210x.ko | head -c 50
<!DOCTYPE html><html lang="en" data-color-mode="au

Looks like an HTML document, right? So , wrong way of downloading?

**Comment by robertklep** [comment]
No output whatsoever? That's not right.

**Comment by fwiegers** [comment]
![Schermafbeelding 2023-05-05 103719](https://user-images.githubusercontent.com/124038604/236412916-699e1ab4-e847-448c-87c3-9bf5baf1f305.jpg)
Looks like it's an HTML document? So wrong way of downloading?

**Comment by robertklep** [comment]
Yes, if it's HTML you downloaded the Github page source and not the actual module.

The correct URL is this: https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/apollolake/dsm-7.2/cp210x.ko

**Comment by fwiegers** [comment]
Thank you very much. wget with the url, followed by the chmod, followed by insmod and now everything works!

**Comment by tonnisjan** [comment]
Does this also working for the 7.4-90075

**Comment by baylanger** [comment]
> Does this also working for the 7.4-90075

Yes

**Comment by tonnisjan** [comment]
Thanks, what can happen in the worse case situation I mean with the next update of dsm7. Will it remove the driver? or an update is not possible anymore?
