### ISSUE TITLE
DSM 7.1 DS2125J

### ISSUE THREAD

**Issue by michaeldn** [robertklep/dsm7-usb-serial-drivers#89]
I have a DS215J with the Armada375. I followed your instructions, but my device (RFLink - Adrino Mega) is on the USB, but not read via the serial port.

I am not certain what is not correct.

**Comment by robertklep** [comment]
Can you run this command and post its output here:
```
/usr/syno/bin/lsusb -cui
```

**Comment by michaeldn** [comment]
usbserial              24729  1 ftdi_sio
usbcore               151242  10 ehci_hcd,xhci_hcd,etxhci_hcd,usb_storage,usblp,usbhid,usbserial,ftdi_sio,cdc_acm

**Comment by robertklep** [comment]
`ch341` should be in that list if it was loaded properly.

**Comment by michaeldn** [comment]
Same result - should I reboot the NAS?

**Comment by robertklep** [comment]
What happens when you load `ch341.ko` manually?
```
sudo insmod /lib/modules/ch341.ko
```

**Comment by michaeldn** [comment]
`insmod: ERROR: could not insert module /lib/modules/ch341.ko: Invalid module format`

**Comment by robertklep** [comment]
That means you didn't follow [the download directions](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module) correctly.

The correct download link is this one: https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/armada375/dsm-7.0/ch341.ko

**Comment by michaeldn** [comment]
That worked thank you! One more question: how do I find the port?

`dmesg | grep tty
[    0.000000] Kernel command line: console=ttyS0,115200 ip=off initrd=0x8000000 root=/dev/md0 rw syno_hw_version=DS215jv10 hd_power_on_seq=2 ihd_num=2 netif_num=1 flash_size=8
[    2.859992] serial8250.0: ttyS0 at MMIO 0xf1012000 (irq = 44) is a 16550A
[    3.586761] console [ttyS0] enabled
[    3.619724] serial8250.1: ttyS1 at MMIO 0xf1012100 (irq = 45) is a 16550A
[   44.658706] synobios open /dev/ttyS1 success
[   61.310107] systemd[1]: Created slice system-serial\x2dgetty.slice.
[   61.317162] systemd[1]: Starting system-serial\x2dgetty.slice.
[   63.330304] synobios open /dev/ttyS1 success
[515201.623975] usb 2-1: ch341-uart converter now attached to ttyUSB0`

**Comment by robertklep** [comment]
It should be available as `/dev/ttyUSB0`

**Comment by michaeldn** [comment]
Hi - after enabling logging and checking everything I realize I am receiving: `Permission denied: '/dev/ttyUSB0' ` 

Do you have any advice on resolving this? Thank you again.

**Comment by robertklep** [comment]
@michaeldn

```
sudo chmod 666 /dev/ttyUSB0
```

**Comment by michaeldn** [comment]
Thank you! My Unix memory is from over a decade ago.
