### ISSUE TITLE
CH343 for apollolake

### ISSUE THREAD

**Issue by monkiibiz** [robertklep/dsm7-usb-serial-drivers#90]
Any chance of getting an apollolake-compatible CH343 driver for DSM 7.1 and/or 7.2?

Stupid me went out and bought a ZBDongle-E instead of ZBDongle-P...

**Comment by robertklep** [comment]
Check out https://github.com/robertklep/dsm7-usb-serial-drivers/blob/main/modules/apollolake/dsm-7.2/ch343.ko

**Comment by monkiibiz** [comment]
Thank you very much!
