### ISSUE TITLE
DMS 7.2 supported?

### ISSUE THREAD

**Issue by ragnarwessels** [robertklep/dsm7-usb-serial-drivers#91]
Does anyone know if these drivers work on the new DSM 7.2?

**Comment by robertklep** [comment]
Do you mean a _specific_ DSM 7.2, or just DSM 7.2 in general?

For most platforms, drivers for DSM 7.2 are available, check out [the modules/ folder](https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules) and your platform to see if they are available for your platform.

**Comment by ragnarwessels** [comment]
I meant 7.2 in general.

I missed that the drivers were uploaded to the modules folders though.
Thanks for the help. I'll grab them from there :-)
