### ISSUE TITLE
Avoton - DSM 7.1 - CH9102/CH343

### ISSUE THREAD

**Issue by hiewliwen** [robertklep/dsm7-usb-serial-drivers#93]
Please build a CH9102/CH343 driver for DSM 7.1 Avoton. Thank you. (DS415+)

**Comment by hiewliwen** [comment]
Thanks. Didn't help in my case. Still fails at "Fails to Probe".

**Comment by robertklep** [comment]
What type of device is it?

And what does the following command show?
```
/usr/syno/bin/lsusb -cui
```

**Comment by hiewliwen** [comment]
Sorry. PEBCAK
I passed /dev/ttyACM0 as folder instead of device in portainer. 
SOLVED!

**Comment by robertklep** [comment]
Good to hear!
