### ISSUE TITLE
DS1520+ with DSM 7.2-64570 Update 1 install modules error

### ISSUE THREAD

**Issue by d9394** [robertklep/dsm7-usb-serial-drivers#94]
ash-4.4# ./start-usb-drivers.sh start
insmod: ERROR: could not insert module /lib/modules/ch341.ko: Invalid module format
insmod: ERROR: could not insert module /lib/modules/cp210x.ko: Invalid module format
insmod: ERROR: could not insert module /lib/modules/pl2303.ko: Invalid module format
insmod: ERROR: could not insert module /lib/modules/ti_usb_3410_5052.ko: Invalid module format
ash-4.4# uname -r
4.4.302+
ash-4.4# uname -a
Linux NAS 4.4.302+ #64570 SMP Tue Jun 13 21:39:55 CST 2023 x86_64 GNU/Linux synology_geminilake_1520+
ash-4.4#

**Comment by robertklep** [comment]
Please follow the [download instructions](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module) carefully.

**Comment by d9394** [comment]
OK, thanks
