### ISSUE TITLE
USB support for geminilake DSM 7.2 

### ISSUE THREAD

**Issue by Masadido** [robertklep/dsm7-usb-serial-drivers#98]
Hello,

Did anyone manage to compile and run the USB drivers for Synology DSM 7.2 Geminilake?
No success so far and the drivers I tried even managed to crash my Synology NAS :-(

Cheers,

**Comment by robertklep** [comment]
Do you mean the provided drivers for [Geminilake 7.2](https://github.com/robertklep/dsm7-usb-serial-drivers/tree/main/modules/geminilake/dsm-7.2) aren't working for you?

**Comment by Masadido** [comment]
I had a severe crash of my system after using those drivers. 
Not sure what happened so I would like to make sure at least someone managed to make them work before trying again...

**Comment by robertklep** [comment]
But from what I understood your issue was related to the "alternative" installation method and not so much the drivers themselves?

**Comment by Masadido** [comment]
Yes indeed, that's my best guess... took me 2 days to recover from last crash so I'm a bit careful now :-)

**Comment by c4coer** [comment]
Good morning,
have you tested?

it works ?

**Comment by Masadido** [comment]
Just a quick update. I tried again with method 1 and it seems to work this time (Geminilake drivers, DS920+, DSM 7.2).

What I did:
- Download the drivers (from this project)
- then SSH and did the following. It seems rndis_host.ko is not required.

sudo su

modprobe usbserial
modprobe ftdi_sio
modprobe cdc-acm

cd /lib/modules/

cp [sourcedirectory]/ch341.ko /lib/modules/ 
sudo insmod /lib/modules/ch341.ko

cp [sourcedirectory]/cp210x.ko /lib/modules/
sudo insmod /lib/modules/cp210x.ko

cp [sourcedirectory]/pl2303.ko /lib/modules/
sudo insmod /lib/modules/pl2303.ko

cp [sourcedirectory]/ti_usb_3410_5052.ko /lib/modules/
sudo insmod /lib/modules/ti_usb_3410_5052.ko

# Configure an autoload script
cd  /usr/local/etc/rc.d/
cp [sourcedirectory]/ti_usb_3410_5052.ko /usr/local/etc/rc.d/usb-serial-drivers.sh
sudo chmod +x usb-serial-drivers.sh

# Make sure your devices are recongnized
sudo /usr/local/etc/rc.d/usb-serial-drivers.sh start

**Comment by MPowerData** [comment]
I followed your stepts, but still am getting:

ERROR: could not insert module /lib/modules/cp210x.ko: Invalid module format

Any idea on how to debug this further?

**Comment by robertklep** [comment]
> ERROR: could not insert module /lib/modules/cp210x.ko: Invalid module format

That means you didn't follow [the downloading instructions](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module) 😋

**Comment by MPowerData** [comment]
> > ERROR: could not insert module /lib/modules/cp210x.ko: Invalid module format
> 
> That means you didn't follow [the downloading instructions](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module) 😋

My bad, thanks for your quick reponse! Working now. :-)

**Comment by robertklep** [comment]
@tadams143 without any more information I have no idea what you're doing wrong 🤷🏼‍♂️

Are you able to load the modules without problems?

**Comment by tadams143** [comment]
Sorry yeah I am not sure how to give more information, but thank you for your fast response. I have loaded all modules apart from rndis_host.ko, which it is my understanding it is unnecessary.

When I run the script it doesnt seem like anything happens, but there aren't any errors.

If i follow through the instructions again all modules say that the file exists.

**Comment by robertklep** [comment]
@tadams143 that sounds like the modules loaded okay.

What does the output of this command show?
```
/usr/syno/bin/lsusb -cui
```

**Comment by condoevil** [comment]
> Just a quick update. I tried again with method 1 and it seems to work this time (Geminilake drivers, DS920+, DSM 7.2).
> 
> What I did:
> 
> * Download the drivers (from this project)
> * then SSH and did the following. It seems rndis_host.ko is not required.
> 


Hi, i downloaded the files but (i'm new to linux command and issues) where should i copy those files before installation? in my PC (MAC) or on the synology?
Many thanks!

**Comment by robertklep** [comment]
@condoevil they need to be installed on your Synology, so that's where they ultimately need to end up 😊

**Comment by condoevil** [comment]
> @condoevil they need to be installed on your Synology, so that's where they ultimately need to end up 😊

@robertklep ok, but i actually don't know the procedure to put those files in the right place. Now i downloaded on my mac using chrome and they are in my download folder. How to proceed? Many thanks for your support, Sorry but i'm a beginner with linux things.

**Comment by robertklep** [comment]
@condoevil all those commands should be executed on your Synology, which _also_ means that you need to set up SSH access to it so you can log in and execute those commands. I can't help with setting that up, but I'm sure there are plenty of tutorials to be found that explain how to get that part working.

Once you've logged in, perhaps it's easier to just download the files to your Synology directly. Which platform/Synology do you have, and which version of DSM is it running?

**Comment by condoevil** [comment]
@robertklep running 7.2 and already have SSH access with SU permissions. I'm only missing all the procedure to follow next.
Synology is DS220+ and should be geminilake.

Many thanks!

**Comment by robertklep** [comment]
@condoevil 

This is how you can download the files directly to DSM, from SSH:
```
cd /lib/modules
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/geminilake/dsm-7.2/ch341.ko
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/geminilake/dsm-7.2/cp210x.ko
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/geminilake/dsm-7.2/pl2303.ko
```

**Comment by condoevil** [comment]
@robertklep Thank you!!!
after that i should proceed with the sudo insmod /lib/modules/... commands right?

**Comment by robertklep** [comment]
@condoevil correct!

**Comment by condoevil** [comment]
@robertklep i arrived to the last command and:
ash-4.4# sudo /usr/local/etc/rc.d/usb-serial-drivers.sh start
/usr/local/etc/rc.d/usb-serial-drivers.sh: line 1: payload:allShortcutsEnabled:false: command not found.
What should i do?

**Comment by robertklep** [comment]
@condoevil looks like you didn't download the file correctly.

Here's how to download it directly to DSM:
```
cd /usr/local/etc/rc.d
sudo wget https://raw.githubusercontent.com/robertklep/dsm7-usb-serial-drivers/main/usb-serial-drivers.sh
sudo chmod 755 usb-serial-drivers.sh
```

**Comment by condoevil** [comment]
@robertklep ok, now it is ok.
What should i do now? dongle working already in Home assistant o should i do something else?

**Comment by robertklep** [comment]
@condoevil I assume that your goal was to get it working in HA, so goal achieved?

**Comment by condoevil** [comment]
@robertklep Homeassistant is asking me for the path of the serial device. What should i insert there?

**Comment by robertklep** [comment]
@condoevil are you running HA in Docker? If so, you first need to make sure the serial device gets passed to the container.

You should be able to find the device entry on the DSM side using `/usr/syno/bin/lsusb -cui`

**Comment by condoevil** [comment]
@robertklep this is what i find:
ash-4.4# /usr/syno/bin/lsusb -cui
|__usb1          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.302+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__1-2         10c4:ea60:0100 00  2.00   12MBit/s 100mA 1IF  (ITead Sonoff Zigbee 3.0 USB Dongle Plus c623c6b3ac29ec11a6e7bf9c40c9ce8d)
  1-2:1.0         (IF) ff:00:00 2EPs () cp210x ttyUSB0 
  |__1-4         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 6500259E98EF6042)
  1-4:1.0         (IF) 08:06:50 2EPs () usb-storage host2 (synoboot)
ash-4.4#

**Comment by robertklep** [comment]
@condoevil okay, so the device entry is `/dev/ttyUSB0`

**Comment by condoevil** [comment]
@robertklep 

<img width="440" alt="Screenshot 2023-09-23 alle 12 14 43" src="https://github.com/robertklep/dsm7-usb-serial-drivers/assets/100016982/2178061d-0242-4cf6-9576-640a2e119152">

it says impossible to connect...

**Comment by condoevil** [comment]
@robertklep 
<img width="759" alt="Screenshot 2023-09-23 alle 12 21 57" src="https://github.com/robertklep/dsm7-usb-serial-drivers/assets/100016982/9e830422-6c45-4fc1-bd62-9a7d292dbd2e">

it is listed in the /dev/ folder

**Comment by robertklep** [comment]
> it says impossible to connect...

It's still not clear to me if you're using Docker, because like I said, if so, you need to pass the device to the container. I don't remember how specifically to do that on DSM since I stopped using it a while ago.

It could also be a permissions problem, try this:
```
sudo chmod 666 /dev/ttyUSB0
```

**Comment by condoevil** [comment]
> > it says impossible to connect...
> 
> It's still not clear to me if you're using Docker, because like I said, if so, you need to pass the device to the container. I don't remember how specifically to do that on DSM since I stopped using it a while ago.
> 
> It could also be a permissions problem, try this:
> 
> ```
> sudo chmod 666 /dev/ttyUSB0
> ```

@robertklep many thanks! finally i installed MQTT and zigbee2MQTT.
Are you able to explain me how to add devices now or may i ask to someone else?

**Comment by robertklep** [comment]
@condoevil you mean add devices to z2m? That's really beyond the scope of this repository, I'm sure you'll find plenty of information on the [z2m website](https://www.zigbee2mqtt.io/).

**Comment by condoevil** [comment]
@robertklep Many thanks for everything! Have a nice day!!!

**Comment by mvroosmalen1970** [comment]
Tried to install, but stuck at : insmod: ERROR: could not insert module /lib/modules/ch341.ko: Invalid module format

I downloaded the modules using:
cd /lib/modules
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/geminilake/dsm-7.2/ch341.ko
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/geminilake/dsm-7.2/cp210x.ko
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/raw/main/modules/geminilake/dsm-7.2/pl2303.ko

Whats wrong????

**Comment by robertklep** [comment]
@mvroosmalen1970 I have no idea what's wrong.

Can you post some more info:
* the output of `uname -a`
* the output of `lsusb -cui`
* the output of `dmesg | tail` right after trying to run `insmod`

Did you load `usbserial.ko` before loading the downloaded modules?

**Comment by mvroosmalen1970** [comment]
> @mvroosmalen1970 I have no idea what's wrong.
> 
> Can you post some more info:
> 
> * the output of `uname -a`
> * the output of `lsusb -cui`
> * the output of `dmesg | tail` right after trying to run `insmod`
> 
> Did you load `usbserial.ko` before loading the downloaded modules?

Hi 

Solved it via: https://mariushosting.com/synology-how-to-add-usb-support-on-dsm-7/

using this tutorial the USB device is recognized automatically

Mark
