### ISSUE TITLE
dsm 7.2-64561   DS920+

### ISSUE THREAD

**Issue by HanTsai7922** [robertklep/dsm7-usb-serial-drivers#99]
**THIS IS NOT A BUG**

Please follow the downloading instructions carefully:
https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module

If you did and it still gives this error, please continue creating an issue report.
--------------------------------------------------------------------------------------------------------
MY device is DS920+ which version is dsm 7.2-64561.

sudo su

modprobe usbserial
modprobe ftdi_sio
modprobe cdc-acm

cd /lib/modules/

sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/blob/main/modules/geminilake/dsm-7.2/ch341.ko
sudo insmod /lib/modules/ch341.ko
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/blob/main/modules/geminilake/dsm-7.2/cp210x.ko
sudo insmod /lib/modules/cp210x.ko
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/blob/main/modules/geminilake/dsm-7.2/pl2303.ko
sudo insmod /lib/modules/pl2303.ko
sudo wget https://github.com/robertklep/dsm7-usb-serial-drivers/blob/main/modules/geminilake/dsm-7.2/ti_usb_3410_5052.ko
sudo insmod /lib/modules/ti_usb_3410_5052.ko

When the process runs error:
root@XXXX:/lib/modules# sudo insmod /lib/modules/ch341.ko.5
insmod: ERROR: could not insert module /lib/modules/ch341.ko.5: Invalid module format

What can i do?
Could you help me solve the problem?

**Comment by robertklep** [comment]
> insmod: ERROR: could not insert module /lib/modules/ch341.ko.5: Invalid module format

The solution is at the top of your post: [**follow the downloading instructions carefully**](https://github.com/robertklep/dsm7-usb-serial-drivers#downloading-a-module).

You're not downloading the modules, you're downloading the HTML page.
